In [3]:
import pandas as p 
df_full = p.read_csv("D1.csv")
df_clean = p.DataFrame()
df_full.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,D1,22/08/2025,19:30,Bayern Munich,RB Leipzig,6,0,H,3,0,...,1.98,1.88,1.98,1.93,1.99,1.93,1.90,1.86,2.07,1.92
1,D1,23/08/2025,14:30,Ein Frankfurt,Werder Bremen,4,1,H,2,0,...,1.83,2.03,2.02,1.91,1.91,2.03,1.83,1.93,1.91,2.06
2,D1,23/08/2025,14:30,Freiburg,Augsburg,1,3,A,0,3,...,1.93,1.93,1.97,1.95,1.97,1.93,1.90,1.86,2.03,1.96
3,D1,23/08/2025,14:30,Heidenheim,Wolfsburg,1,3,A,1,1,...,2.03,1.83,2.06,1.87,2.03,1.85,1.97,1.81,2.12,1.88
4,D1,23/08/2025,14:30,Leverkusen,Hoffenheim,1,2,A,1,1,...,1.98,1.88,1.97,1.95,1.98,2.02,1.88,1.86,2.00,1.97

In [4]:
team_s = sorted(df_full['HomeTeam'].unique())
team_map = {team:i for i,team in enumerate(team_s)}
team_map

{'Augsburg': 0,
 'Bayern Munich': 1,
 'Dortmund': 2,
 'Ein Frankfurt': 3,
 'FC Koln': 4,
 'Freiburg': 5,
 'Hamburg': 6,
 'Heidenheim': 7,
 'Hoffenheim': 8,
 'Leverkusen': 9,
 "M'gladbach": 10,
 'Mainz': 11,
 'RB Leipzig': 12,
 'St Pauli': 13,
 'Stuttgart': 14,
 'Union Berlin': 15,
 'Werder Bremen': 16,
 'Wolfsburg': 17}

In [6]:
df_clean['HomeTeam']=df_full['HomeTeam'].map(team_map)
df_clean['AwayTeam'] = df_full['AwayTeam'].map(team_map)
df_clean.head()

   HomeTeam  AwayTeam
0         1        12
1         3        16
2         5         0
3         7        17
4         9         8

In [7]:
df_clean['homeGoalDiff'] = df_full['FTHG']-df_full['FTAG']
df_clean.head()

   HomeTeam  AwayTeam  homeGoalDiff
0         1        12             6
1         3        16             3
2         5         0            -2
3         7        17            -2
4         9         8            -1